### ISSUE TITLE
[Request] Detailed list of required files

### ISSUE THREAD

**Issue by NightFright2k19** [jval1972/Mars3D#1]
The DOS release comes with a lot of files and many certainly are not required to run this port (e.g. any of the old .exe binaries). It would be nice to have a list with the exact lineup of all Mars3D data files which are needed.

**Comment by jval1972** [comment]
Here is the list: https://raw.githubusercontent.com/jval1972/Mars3D/df5004cda0867e860d97eff194bc124dde7d8a20/files.txt

**Comment by NightFright2k19** [comment]
Excellent! Thanks!
