### ISSUE TITLE
Crash on startup due to missing FOGMAP

### ISSUE THREAD

**Issue by PerdGateEnjoyer** [jval1972/Mars3D#4]
![image](https://github.com/jval1972/Mars3D/assets/135927009/0dad3adc-01c5-4f01-9e14-cffc8838d711)

**Comment by jval1972** [comment]
Make sure that  file FOGTABLE.DAT exists.

**Comment by PerdGateEnjoyer** [comment]
okie doke

**Comment by PerdGateEnjoyer** [comment]
Dumb, had files in wrong spot
